from datetime import time

from django.core.management.base import BaseCommand

from travel.models import Destination, HolidayPackage, Hotel, TransportOption, TripBooking


class Command(BaseCommand):
    help = "Create demo destinations, hotels, transport options, and holiday packages."

    def handle(self, *args, **options):
        TripBooking.objects.all().delete()
        Destination.objects.all().delete()

        destination_data = [
            {
                "key": "bengaluru",
                "name": "Bengaluru",
                "country": "India",
                "description": "Tech parks, cafes, gardens, breweries, shopping, and easy weekend getaways.",
                "best_season": "October to February",
                "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "mumbai",
                "name": "Mumbai",
                "country": "India",
                "description": "Sea views, nightlife, heritage streets, business hubs, food trails, and luxury stays.",
                "best_season": "November to February",
                "image_url": "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "goa",
                "name": "Goa",
                "country": "India",
                "description": "Sunny beaches, seafood cafes, forts, and relaxed coastal evenings.",
                "best_season": "October to March",
                "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "manali",
                "name": "Manali",
                "country": "India",
                "description": "Snow views, pine forests, adventure sports, and mountain cafes.",
                "best_season": "March to June",
                "image_url": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "jaipur",
                "name": "Jaipur",
                "country": "India",
                "description": "Palaces, bazaars, forts, museums, and colorful local food.",
                "best_season": "November to February",
                "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "kerala",
                "name": "Kerala",
                "country": "India",
                "description": "Backwaters, houseboats, spice gardens, beaches, and calm village stays.",
                "best_season": "September to March",
                "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "varanasi",
                "name": "Varanasi",
                "country": "India",
                "description": "River ghats, temples, evening aarti, silk markets, and heritage walks.",
                "best_season": "October to March",
                "image_url": "https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "udaipur",
                "name": "Udaipur",
                "country": "India",
                "description": "Lakes, palaces, boat rides, art streets, and romantic sunset viewpoints.",
                "best_season": "September to March",
                "image_url": "https://images.unsplash.com/photo-1586612432563-5e30750fc720?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "rishikesh",
                "name": "Rishikesh",
                "country": "India",
                "description": "River rafting, yoga retreats, suspension bridges, cafes, and forest trails.",
                "best_season": "February to May",
                "image_url": "https://images.unsplash.com/photo-1627894006066-b4576f0268ab?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "darjeeling",
                "name": "Darjeeling",
                "country": "India",
                "description": "Tea gardens, toy train rides, hill views, monasteries, and cozy cafes.",
                "best_season": "March to May",
                "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "andaman",
                "name": "Andaman",
                "country": "India",
                "description": "Blue water beaches, coral reefs, scuba diving, island hopping, and quiet resorts.",
                "best_season": "November to April",
                "image_url": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "agra",
                "name": "Agra",
                "country": "India",
                "description": "Mughal monuments, the Taj Mahal, marble craft markets, and heritage food trails.",
                "best_season": "October to March",
                "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "dubai",
                "name": "Dubai",
                "country": "United Arab Emirates",
                "description": "Skylines, desert safaris, shopping districts, beaches, and luxury resorts.",
                "best_season": "November to March",
                "image_url": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "singapore",
                "name": "Singapore",
                "country": "Singapore",
                "description": "Gardens, waterfront attractions, street food, shopping, and family entertainment.",
                "best_season": "February to April",
                "image_url": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "bali",
                "name": "Bali",
                "country": "Indonesia",
                "description": "Beaches, temples, rice terraces, wellness stays, and island adventures.",
                "best_season": "April to October",
                "image_url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "london",
                "name": "London",
                "country": "United Kingdom",
                "description": "Museums, theatres, markets, riverside walks, royal landmarks, and global dining.",
                "best_season": "May to September",
                "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "paris",
                "name": "Paris",
                "country": "France",
                "description": "Art museums, cafes, river cruises, fashion streets, and iconic monuments.",
                "best_season": "April to June",
                "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80",
            },
            {
                "key": "maldives",
                "name": "Maldives",
                "country": "Maldives",
                "description": "Overwater villas, coral reefs, beaches, diving, and private island resorts.",
                "best_season": "November to April",
                "image_url": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=900&q=80",
            },
        ]

        destinations = {}
        for item in destination_data:
            key = item.pop("key")
            destinations[key] = Destination.objects.create(**item)

        hotels = [
            ("goa", "Palm Breeze Resort", "Calangute Beach Road", 4, 4200, "Pool, breakfast, Wi-Fi"),
            ("goa", "Casa Marina Stay", "Baga Lane", 3, 2600, "Breakfast, parking, beach access"),
            ("goa", "Blue Tide Hostel", "Anjuna Market Road", 2, 1400, "Shared lounge, lockers, Wi-Fi"),
            ("manali", "Snow Pine Retreat", "Old Manali", 4, 3800, "Heater, mountain view, Wi-Fi"),
            ("manali", "River Nest Lodge", "Kullu Road", 3, 2200, "River view, breakfast, bonfire"),
            ("manali", "Cedar Backpackers", "Hadimba Road", 2, 1200, "Dorm beds, cafe, trekking desk"),
            ("jaipur", "Pink City Heritage Inn", "MI Road", 4, 3500, "Rooftop dining, Wi-Fi, parking"),
            ("jaipur", "Amber Courtyard Hotel", "Amer Road", 3, 2400, "Breakfast, city tours, cab desk"),
            ("jaipur", "Royal Haveli Suites", "Bani Park", 5, 7800, "Pool, spa, heritage rooms"),
            ("kerala", "Backwater Pearl Houseboat", "Alleppey Jetty", 4, 6200, "Meals, lake cruise, private deck"),
            ("kerala", "Spice Garden Homestay", "Munnar Tea Estate Road", 3, 2800, "Breakfast, garden walk, Wi-Fi"),
            ("varanasi", "Ganga View Residency", "Dashashwamedh Ghat", 4, 4600, "River view, aarti access, breakfast"),
            ("varanasi", "Kashi Comfort Stay", "Godowlia Road", 3, 1900, "Wi-Fi, local guide, breakfast"),
            ("udaipur", "Lake Palace View Hotel", "Lake Pichola Road", 4, 5200, "Lake view, rooftop dining, Wi-Fi"),
            ("udaipur", "Aravali Budget Rooms", "Hathipole", 2, 1600, "Parking, breakfast, travel desk"),
            ("rishikesh", "Ganga Riverside Camp", "Shivpuri", 3, 2100, "Rafting desk, meals, bonfire"),
            ("rishikesh", "Yoga Valley Retreat", "Tapovan", 4, 4300, "Yoga sessions, cafe, Wi-Fi"),
            ("darjeeling", "Tea Mist Resort", "Lebong Cart Road", 4, 4100, "Tea garden view, heater, breakfast"),
            ("darjeeling", "Hilltop Traveller Hostel", "Mall Road", 2, 1300, "Dorm beds, Wi-Fi, common room"),
            ("andaman", "Coral Bay Resort", "Havelock Island", 4, 6800, "Beach access, dive desk, breakfast"),
            ("andaman", "Island Breeze Inn", "Port Blair", 3, 3100, "Airport pickup, Wi-Fi, cafe"),
            ("agra", "Taj Sunrise Hotel", "Taj East Gate Road", 4, 3900, "Rooftop view, breakfast, Wi-Fi"),
            ("agra", "Mughal Budget Stay", "Fatehabad Road", 2, 1500, "Parking, city tours, Wi-Fi"),
            ("bengaluru", "Indiranagar Business Hotel", "Indiranagar", 4, 6400, "Breakfast, metro access, business desk"),
            ("bengaluru", "Garden City Premium", "MG Road", 5, 11500, "Pool, breakfast, airport transfer"),
            ("bengaluru", "Whitefield Comfort Suites", "Whitefield", 3, 4200, "Wi-Fi, workspace, breakfast"),
            ("mumbai", "Marine Drive Grand", "Marine Drive", 5, 15400, "Sea view, breakfast, pool"),
            ("mumbai", "Bandra Boutique Hotel", "Bandra West", 4, 9300, "Cafe, Wi-Fi, airport transfer"),
            ("mumbai", "Airport Transit Rooms", "Andheri East", 3, 5100, "Airport pickup, breakfast, Wi-Fi"),
            ("dubai", "Marina Skyline Hotel", "Dubai Marina", 5, 14500, "Pool, city view, airport transfer"),
            ("dubai", "Desert Palm Suites", "Al Barsha", 4, 8900, "Breakfast, metro access, Wi-Fi"),
            ("singapore", "Bayfront Premier Stay", "Marina Bay", 5, 16800, "Infinity pool, breakfast, city view"),
            ("singapore", "Orchard City Hotel", "Orchard Road", 4, 11200, "Shopping access, breakfast, Wi-Fi"),
            ("bali", "Ubud Garden Villas", "Ubud", 4, 7600, "Private pool, breakfast, scooter desk"),
            ("bali", "Kuta Beach Resort", "Kuta", 3, 5200, "Beach access, cafe, Wi-Fi"),
            ("london", "Westminster Central Hotel", "Westminster", 4, 18200, "Breakfast, tube access, Wi-Fi"),
            ("london", "Camden Boutique Rooms", "Camden Town", 3, 12600, "Market access, Wi-Fi, lounge"),
            ("paris", "Seine View Residence", "Latin Quarter", 4, 17100, "River view, breakfast, metro access"),
            ("paris", "Montmartre Comfort Inn", "Montmartre", 3, 11900, "Cafe, Wi-Fi, city tours"),
            ("maldives", "Lagoon Overwater Resort", "North Male Atoll", 5, 29500, "Villa deck, meals, snorkeling"),
            ("maldives", "Coral Sands Island Stay", "Maafushi", 4, 13400, "Beach access, dive desk, breakfast"),
        ]
        hotel_images = [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1495365200479-c4ed1d35e1aa?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1519821172141-b5d8d1a70481?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1521783988139-89397d761dce?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=900&q=80",
        ]
        for index, hotel in enumerate(hotels):
            destination_key, name, address, rating, price, amenities = hotel
            Hotel.objects.create(
                destination=destinations[destination_key],
                name=name,
                address=address,
                star_rating=rating,
                price_per_night=price,
                rooms_available=12 + index,
                amenities=amenities,
                image_url=destinations[destination_key].image_url,
            )

        TransportOption.objects.bulk_create(
            [
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Akasa Air",
                    departure_time=time(6, 10),
                    arrival_time=time(8, 55),
                    price=8738,
                    seats_available=31,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="IndiGo",
                    departure_time=time(7, 45),
                    arrival_time=time(10, 35),
                    price=8910,
                    seats_available=44,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Air India",
                    departure_time=time(9, 20),
                    arrival_time=time(12, 10),
                    price=12995,
                    seats_available=20,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="SpiceJet",
                    departure_time=time(13, 15),
                    arrival_time=time(16, 5),
                    price=8578,
                    seats_available=27,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Vistara",
                    departure_time=time(18, 30),
                    arrival_time=time(21, 20),
                    price=11150,
                    seats_available=18,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Air India Express",
                    departure_time=time(22, 55),
                    arrival_time=time(1, 45),
                    price=9203,
                    seats_available=37,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="IndiGo",
                    departure_time=time(6, 0),
                    arrival_time=time(7, 45),
                    price=6450,
                    seats_available=46,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Akasa Air",
                    departure_time=time(20, 10),
                    arrival_time=time(21, 55),
                    price=6100,
                    seats_available=25,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["mumbai"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Vistara",
                    departure_time=time(8, 50),
                    arrival_time=time(11, 5),
                    price=7800,
                    seats_available=34,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["mumbai"],
                    transport_type=TransportOption.PLANE,
                    provider_name="IndiGo",
                    departure_time=time(16, 35),
                    arrival_time=time(18, 50),
                    price=7250,
                    seats_available=40,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["goa"],
                    transport_type=TransportOption.PLANE,
                    provider_name="SkyJet Airways",
                    departure_time=time(8, 30),
                    arrival_time=time(9, 45),
                    price=5200,
                    seats_available=35,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["goa"],
                    transport_type=TransportOption.BUS,
                    provider_name="Coastal Express",
                    departure_time=time(21, 0),
                    arrival_time=time(8, 0),
                    price=1500,
                    seats_available=22,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["manali"],
                    transport_type=TransportOption.BUS,
                    provider_name="Himalayan Volvo",
                    departure_time=time(19, 30),
                    arrival_time=time(7, 30),
                    price=1800,
                    seats_available=18,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["manali"],
                    transport_type=TransportOption.CAB,
                    provider_name="Mountain Cabs",
                    departure_time=time(6, 0),
                    arrival_time=time(18, 0),
                    price=9500,
                    seats_available=4,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["jaipur"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Rajdhani Rail",
                    departure_time=time(6, 10),
                    arrival_time=time(10, 35),
                    price=1100,
                    seats_available=60,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["jaipur"],
                    transport_type=TransportOption.BUS,
                    provider_name="Desert Line Travels",
                    departure_time=time(7, 0),
                    arrival_time=time(13, 0),
                    price=900,
                    seats_available=28,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Karnataka Rajdhani",
                    departure_time=time(20, 45),
                    arrival_time=time(6, 40),
                    price=3150,
                    seats_available=80,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Duronto Express",
                    departure_time=time(23, 15),
                    arrival_time=time(8, 30),
                    price=2850,
                    seats_available=66,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.BUS,
                    provider_name="IntrCity SmartBus",
                    departure_time=time(18, 0),
                    arrival_time=time(12, 30),
                    price=2450,
                    seats_available=29,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.BUS,
                    provider_name="Orange Tours",
                    departure_time=time(20, 15),
                    arrival_time=time(15, 0),
                    price=2650,
                    seats_available=21,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.CAB,
                    provider_name="Premium Intercity Cabs",
                    departure_time=time(5, 0),
                    arrival_time=time(3, 30),
                    price=42000,
                    seats_available=4,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bengaluru"],
                    transport_type=TransportOption.CAB,
                    provider_name="Executive Roadways",
                    departure_time=time(7, 30),
                    arrival_time=time(6, 0),
                    price=45500,
                    seats_available=6,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["goa"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Konkan Express",
                    departure_time=time(7, 10),
                    arrival_time=time(18, 20),
                    price=900,
                    seats_available=72,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["goa"],
                    transport_type=TransportOption.BUS,
                    provider_name="Paulo Travels",
                    departure_time=time(20, 30),
                    arrival_time=time(7, 15),
                    price=1350,
                    seats_available=22,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["goa"],
                    transport_type=TransportOption.BUS,
                    provider_name="ZingBus",
                    departure_time=time(22, 0),
                    arrival_time=time(8, 50),
                    price=1250,
                    seats_available=18,
                ),
                TransportOption(
                    source="Bengaluru",
                    destination=destinations["goa"],
                    transport_type=TransportOption.BUS,
                    provider_name="SeaBird Travels",
                    departure_time=time(19, 45),
                    arrival_time=time(8, 30),
                    price=1600,
                    seats_available=26,
                ),
                TransportOption(
                    source="Bengaluru",
                    destination=destinations["goa"],
                    transport_type=TransportOption.CAB,
                    provider_name="Coastal Cabs",
                    departure_time=time(5, 30),
                    arrival_time=time(16, 15),
                    price=11800,
                    seats_available=4,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["dubai"],
                    transport_type=TransportOption.BUS,
                    provider_name="Airport Shuttle Partner",
                    departure_time=time(2, 0),
                    arrival_time=time(3, 15),
                    price=900,
                    seats_available=14,
                ),
                TransportOption(
                    source="Dubai",
                    destination=destinations["dubai"],
                    transport_type=TransportOption.CAB,
                    provider_name="Dubai City Transfers",
                    departure_time=time(9, 0),
                    arrival_time=time(10, 10),
                    price=3200,
                    seats_available=4,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["jaipur"],
                    transport_type=TransportOption.CAB,
                    provider_name="Royal Route Cabs",
                    departure_time=time(7, 0),
                    arrival_time=time(12, 0),
                    price=5200,
                    seats_available=4,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["agra"],
                    transport_type=TransportOption.CAB,
                    provider_name="Expressway Cabs",
                    departure_time=time(6, 30),
                    arrival_time=time(10, 0),
                    price=4300,
                    seats_available=4,
                ),
                TransportOption(
                    source="Bengaluru",
                    destination=destinations["kerala"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Malabar Express",
                    departure_time=time(20, 15),
                    arrival_time=time(8, 45),
                    price=1450,
                    seats_available=42,
                ),
                TransportOption(
                    source="Kochi",
                    destination=destinations["kerala"],
                    transport_type=TransportOption.CAB,
                    provider_name="Green Route Cabs",
                    departure_time=time(9, 0),
                    arrival_time=time(12, 30),
                    price=4200,
                    seats_available=4,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["varanasi"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Indigo Connect",
                    departure_time=time(11, 10),
                    arrival_time=time(12, 35),
                    price=4800,
                    seats_available=31,
                ),
                TransportOption(
                    source="Lucknow",
                    destination=destinations["varanasi"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Kashi Intercity",
                    departure_time=time(6, 20),
                    arrival_time=time(12, 10),
                    price=650,
                    seats_available=70,
                ),
                TransportOption(
                    source="Ahmedabad",
                    destination=destinations["udaipur"],
                    transport_type=TransportOption.BUS,
                    provider_name="Lake City Travels",
                    departure_time=time(7, 30),
                    arrival_time=time(13, 15),
                    price=850,
                    seats_available=26,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["udaipur"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Vista Air",
                    departure_time=time(14, 15),
                    arrival_time=time(15, 40),
                    price=5600,
                    seats_available=24,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["rishikesh"],
                    transport_type=TransportOption.BUS,
                    provider_name="Ganga Volvo",
                    departure_time=time(22, 0),
                    arrival_time=time(5, 30),
                    price=950,
                    seats_available=34,
                ),
                TransportOption(
                    source="Dehradun",
                    destination=destinations["rishikesh"],
                    transport_type=TransportOption.CAB,
                    provider_name="Hillline Cabs",
                    departure_time=time(10, 0),
                    arrival_time=time(11, 20),
                    price=1800,
                    seats_available=4,
                ),
                TransportOption(
                    source="Kolkata",
                    destination=destinations["darjeeling"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Darjeeling Mail",
                    departure_time=time(22, 5),
                    arrival_time=time(8, 0),
                    price=1350,
                    seats_available=52,
                ),
                TransportOption(
                    source="Bagdogra",
                    destination=destinations["darjeeling"],
                    transport_type=TransportOption.CAB,
                    provider_name="Tea Valley Cabs",
                    departure_time=time(12, 0),
                    arrival_time=time(15, 15),
                    price=3200,
                    seats_available=4,
                ),
                TransportOption(
                    source="Chennai",
                    destination=destinations["andaman"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Island Air",
                    departure_time=time(7, 45),
                    arrival_time=time(10, 5),
                    price=7400,
                    seats_available=29,
                ),
                TransportOption(
                    source="Port Blair",
                    destination=destinations["andaman"],
                    transport_type=TransportOption.CAB,
                    provider_name="Harbor Transfers",
                    departure_time=time(13, 0),
                    arrival_time=time(15, 30),
                    price=2500,
                    seats_available=5,
                ),
                TransportOption(
                    source="Delhi",
                    destination=destinations["agra"],
                    transport_type=TransportOption.TRAIN,
                    provider_name="Gatimaan Express",
                    departure_time=time(8, 10),
                    arrival_time=time(9, 50),
                    price=750,
                    seats_available=80,
                ),
                TransportOption(
                    source="Jaipur",
                    destination=destinations["agra"],
                    transport_type=TransportOption.BUS,
                    provider_name="Golden Triangle Bus",
                    departure_time=time(6, 45),
                    arrival_time=time(11, 15),
                    price=700,
                    seats_available=32,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["dubai"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Emirates Connect",
                    departure_time=time(4, 10),
                    arrival_time=time(7, 5),
                    price=24500,
                    seats_available=36,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["dubai"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Air India Express",
                    departure_time=time(19, 45),
                    arrival_time=time(22, 25),
                    price=19800,
                    seats_available=41,
                ),
                TransportOption(
                    source="Bengaluru",
                    destination=destinations["singapore"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Singapore Wings",
                    departure_time=time(23, 15),
                    arrival_time=time(6, 20),
                    price=28900,
                    seats_available=33,
                ),
                TransportOption(
                    source="Chennai",
                    destination=destinations["singapore"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Scoot Connect",
                    departure_time=time(1, 30),
                    arrival_time=time(8, 25),
                    price=22600,
                    seats_available=39,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["bali"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Island Hopper Air",
                    departure_time=time(9, 40),
                    arrival_time=time(21, 10),
                    price=34500,
                    seats_available=22,
                ),
                TransportOption(
                    source="Mumbai",
                    destination=destinations["london"],
                    transport_type=TransportOption.PLANE,
                    provider_name="British World",
                    departure_time=time(2, 15),
                    arrival_time=time(7, 45),
                    price=58900,
                    seats_available=18,
                ),
                TransportOption(
                    source="New Delhi",
                    destination=destinations["paris"],
                    transport_type=TransportOption.PLANE,
                    provider_name="EuroSky",
                    departure_time=time(1, 5),
                    arrival_time=time(7, 20),
                    price=54400,
                    seats_available=24,
                ),
                TransportOption(
                    source="Kochi",
                    destination=destinations["maldives"],
                    transport_type=TransportOption.PLANE,
                    provider_name="Ocean Air",
                    departure_time=time(11, 20),
                    arrival_time=time(12, 40),
                    price=21900,
                    seats_available=27,
                ),
            ]
        )

        package_images = [
            "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1516406742981-2b7d67ec4ae8?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1526711657229-e7e080ed7aa1?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1496939376851-89342e90adcd?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1520986606214-8b456906c813?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=900&q=80",
            "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80",
        ]
        HolidayPackage.objects.bulk_create(
            [
                HolidayPackage(
                    destination=destinations["goa"],
                    title="Goa Beach Break",
                    duration_days=4,
                    price_per_person=12999,
                    itinerary="Day 1 beach check-in, Day 2 fort tour, Day 3 island trip, Day 4 shopping.",
                    image_url=package_images[0],
                ),
                HolidayPackage(
                    destination=destinations["manali"],
                    title="Manali Snow Escape",
                    duration_days=5,
                    price_per_person=15999,
                    itinerary="Day 1 arrival, Day 2 Solang Valley, Day 3 local sightseeing, Day 4 adventure sports, Day 5 return.",
                    image_url=package_images[1],
                ),
                HolidayPackage(
                    destination=destinations["jaipur"],
                    title="Jaipur Royal Weekend",
                    duration_days=3,
                    price_per_person=9999,
                    itinerary="Day 1 City Palace, Day 2 Amber Fort and markets, Day 3 museum visit and return.",
                    image_url=package_images[2],
                ),
                HolidayPackage(
                    destination=destinations["kerala"],
                    title="Kerala Backwater Calm",
                    duration_days=5,
                    price_per_person=18999,
                    itinerary="Day 1 Kochi arrival, Day 2 Munnar gardens, Day 3 Alleppey houseboat, Day 4 beach visit, Day 5 return.",
                    image_url=package_images[3],
                ),
                HolidayPackage(
                    destination=destinations["varanasi"],
                    title="Varanasi Heritage Walk",
                    duration_days=3,
                    price_per_person=8499,
                    itinerary="Day 1 ghat walk, Day 2 temple trail and boat ride, Day 3 silk market and return.",
                    image_url=package_images[4],
                ),
                HolidayPackage(
                    destination=destinations["udaipur"],
                    title="Udaipur Lake Weekend",
                    duration_days=4,
                    price_per_person=13999,
                    itinerary="Day 1 lake check-in, Day 2 palace tour, Day 3 boat ride and art lanes, Day 4 return.",
                    image_url=package_images[5],
                ),
                HolidayPackage(
                    destination=destinations["rishikesh"],
                    title="Rishikesh Adventure Camp",
                    duration_days=3,
                    price_per_person=7999,
                    itinerary="Day 1 camp arrival, Day 2 rafting and cafe walk, Day 3 yoga session and return.",
                    image_url=package_images[6],
                ),
                HolidayPackage(
                    destination=destinations["darjeeling"],
                    title="Darjeeling Tea Trail",
                    duration_days=4,
                    price_per_person=11999,
                    itinerary="Day 1 arrival, Day 2 sunrise point and toy train, Day 3 tea estate visit, Day 4 return.",
                    image_url=package_images[7],
                ),
                HolidayPackage(
                    destination=destinations["andaman"],
                    title="Andaman Island Hop",
                    duration_days=6,
                    price_per_person=24999,
                    itinerary="Day 1 Port Blair, Day 2 Havelock, Day 3 scuba day, Day 4 Neil Island, Day 5 beach leisure, Day 6 return.",
                    image_url=package_images[8],
                ),
                HolidayPackage(
                    destination=destinations["agra"],
                    title="Agra Monument Express",
                    duration_days=2,
                    price_per_person=5999,
                    itinerary="Day 1 Taj Mahal and Agra Fort, Day 2 marble market and return.",
                    image_url=package_images[9],
                ),
                HolidayPackage(
                    destination=destinations["dubai"],
                    title="Dubai Skyline and Desert",
                    duration_days=5,
                    price_per_person=64999,
                    itinerary="Day 1 arrival, Day 2 city tour, Day 3 desert safari, Day 4 marina evening, Day 5 return.",
                    image_url=package_images[10],
                ),
                HolidayPackage(
                    destination=destinations["singapore"],
                    title="Singapore Family Escape",
                    duration_days=5,
                    price_per_person=72999,
                    itinerary="Day 1 arrival, Day 2 Sentosa, Day 3 city tour, Day 4 gardens and shopping, Day 5 return.",
                    image_url=package_images[11],
                ),
                HolidayPackage(
                    destination=destinations["bali"],
                    title="Bali Beach and Wellness",
                    duration_days=6,
                    price_per_person=68999,
                    itinerary="Day 1 arrival, Day 2 Ubud, Day 3 temple trail, Day 4 beach leisure, Day 5 spa day, Day 6 return.",
                    image_url=package_images[12],
                ),
                HolidayPackage(
                    destination=destinations["london"],
                    title="London City Explorer",
                    duration_days=6,
                    price_per_person=119999,
                    itinerary="Day 1 arrival, Day 2 royal landmarks, Day 3 museums, Day 4 markets, Day 5 theatre night, Day 6 return.",
                    image_url=package_images[13],
                ),
                HolidayPackage(
                    destination=destinations["paris"],
                    title="Paris Art and Cafe Trail",
                    duration_days=5,
                    price_per_person=109999,
                    itinerary="Day 1 arrival, Day 2 monuments, Day 3 Louvre visit, Day 4 river cruise, Day 5 return.",
                    image_url=package_images[14],
                ),
                HolidayPackage(
                    destination=destinations["maldives"],
                    title="Maldives Lagoon Retreat",
                    duration_days=5,
                    price_per_person=135999,
                    itinerary="Day 1 island transfer, Day 2 snorkeling, Day 3 spa and beach, Day 4 sunset cruise, Day 5 return.",
                    image_url=package_images[15],
                ),
                HolidayPackage(
                    destination=destinations["bengaluru"],
                    title="Bengaluru Food and Brewery Tour",
                    duration_days=2,
                    price_per_person=6999,
                    itinerary="Day 1 cafe crawl and brewery evening, Day 2 gardens, shopping, and city highlights.",
                    image_url=destinations["bengaluru"].image_url,
                ),
                HolidayPackage(
                    destination=destinations["mumbai"],
                    title="Mumbai Sea Link Weekend",
                    duration_days=3,
                    price_per_person=11999,
                    itinerary="Day 1 Marine Drive, Day 2 heritage and street food, Day 3 shopping and departure.",
                    image_url=destinations["mumbai"].image_url,
                ),
                HolidayPackage(
                    destination=destinations["dubai"],
                    title="Dubai Premium Cruise Night",
                    duration_days=3,
                    price_per_person=38999,
                    itinerary="Day 1 marina arrival, Day 2 cruise dinner and skyline tour, Day 3 shopping and return.",
                    image_url=destinations["dubai"].image_url,
                ),
                HolidayPackage(
                    destination=destinations["andaman"],
                    title="Andaman Coastal Cruise",
                    duration_days=4,
                    price_per_person=32999,
                    itinerary="Day 1 Port Blair, Day 2 island cruise, Day 3 beach leisure, Day 4 return.",
                    image_url=destinations["andaman"].image_url,
                ),
            ]
        )

        self.stdout.write(
            self.style.SUCCESS(
                "Demo data created: "
                f"{Destination.objects.count()} destinations, "
                f"{Hotel.objects.count()} hotels, "
                f"{TransportOption.objects.count()} transport options, "
                f"{HolidayPackage.objects.count()} packages."
            )
        )
